logging:
  level:
    me.mprieto: DEBUG

atlassian:
  connect:
    jwtExpirationTime: 1800
    require-auth-exclude-paths:
      - /issues/**
      - /projects/**

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "configprops", "env"]
